language: fortran
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y libudunits-2.0
  - sudo apt-get install -y libnetcdff6
script:
  - mkdir build && cd build && cmake .. && make
